In [1]:
import pandas as pd


# File paths
file_vaccine = "Dataset/VIOLIN_12-10-2025/raw/t_vaccine_202512101310.csv"
file_adjuvant = "Dataset/VIOLIN_12-10-2025/raw/t_adjuvant_202512101312.csv"
file_vaxjo   = "Dataset/VIOLIN_12-10-2025/raw/t_vaxjo_202512101311.csv"
file_pathogen   = "Dataset/VIOLIN_12-10-2025/raw/t_pathogen_202512101313.csv"
file_reference   = "Dataset/VIOLIN_12-10-2025/raw/t_reference_202512101313.csv"



# Load as DataFrames
df_vaccine_raw  = pd.read_csv(file_vaccine, encoding="utf-8-sig") #encoding="utf-8"  # this param is ignored for .xlsx but good practice #encoding='ISO-8859-1', on_bad_lines='warn'
df_adjuvant_raw = pd.read_csv(file_adjuvant, encoding="utf-8-sig")
df_vaxjo_raw    = pd.read_csv(file_vaxjo, encoding="utf-8-sig")
df_pathogen_raw = pd.read_csv(file_pathogen, encoding="utf-8-sig")



# Function to summarize each dataframe
def summarize_df(df, name):
    print(f"\n=== {name} ===")
    print(f"Number of rows: {len(df)}")
    print(f"Number of columns: {df.shape[1]}")
    print("Columns:", df.columns.tolist())
    #print(df.head(3))  # show first 3 rows as preview
    
    

# Summaries
summarize_df(df_vaccine_raw, "t_vaccine")
summarize_df(df_adjuvant_raw, "t_adjuvant")
summarize_df(df_vaxjo_raw, "t_vaxjo")
summarize_df(df_pathogen_raw, "t_pathogen")

=== t_vaccine ===
Number of rows: 5550
Number of columns: 31
Columns: ['c_vaccine_id', 'c_vaccine_name', 'c_type', 'c_is_combination_vaccine', 'c_description', 'c_adjuvant', 'c_storage', 'c_pathogen_id', 'c_virulence', 'c_preparation', 'c_brand_name', 'c_full_text', 'c_antigen', 'c_curation_flag', 'c_vector', 'c_proper_name', 'c_manufacturer', 'c_contraindication', 'c_status', 'c_location_licensed', 'c_host_species', 'c_route', 'c_vo_id', 'c_usage_age', 'c_model_host', 'c_preservative', 'c_allergen', 'c_preparation_vo_id', 'c_host_species2', 'c_cvx_code', 'c_cvx_desc']

=== t_adjuvant ===
Number of rows: 565
Number of columns: 7
Columns: ['c_adjuvant_id', 'c_adjuvant_vo_id', 'c_adjuvant_label', 'c_adjuvant_description', 'c_vaccine_id', 'c_pathogen_id', 'c_curation_flag']

=== t_vaxjo ===
Number of rows: 500
Number of columns: 22
Columns: ['c_vaxjo_id', 'c_components', 'c_function', 'c_dosage', 'c_safety', 'c_vaxjo_vo_id', 'c_vaxjo_name', 'c_submitted_by', 'c_submission_date', 'c_curation_flag', 'c_reviewer', 'c_preparation', 'c_description', 'c_alternative_names', 'c_structure', 'c_appearance', 'c_molecular_weight', 'c_storage', 'c_stage_dev', 'c_location_licensed', 'c_host_licensed', 'c_host_licensed2']

=== t_pathogen ===
Number of rows: 314
Number of columns: 18
Columns: ['c_pathogen_id', 'c_pathogen_name', 'c_taxon_id', 'c_pathogenesis', 'c_disease_name', 'c_protective_immunity', 'c_submitted_by', 'c_submission_date', 'c_curation_flag', 'c_reviewer', 'c_host_range', 'c_full_text', 'c_introduction', 'c_gram', 'c_organism_type', 'c_preparation_vo_id', 'c_vaccine_vo_id', 'c_protein_vo_id']

In [2]:
import os
os.makedirs("Dataset/VIOLIN_12-10-2025/interim", exist_ok=True)

In [3]:
from IPython.display import display

def show_test_rows_full(df, col, n=10):
    if col in df.columns:
        mask = df[col].astype(str).str.lower().str.startswith("test")
        print(f"{col}: {mask.sum()} test rows")
        return df.loc[mask].head(n)
    return None

display(show_test_rows_full(df_adjuvant_raw, "c_adjuvant_label"))
display(show_test_rows_full(df_vaxjo_raw, "c_vaxjo_name"))
display(show_test_rows_full(df_vaccine_raw, "c_vaccine_name"))
display(show_test_rows_full(df_pathogen_raw, "c_pathogen_name"))

c_adjuvant_label: 1 test rows

,c_adjuvant_id,c_adjuvant_vo_id,c_adjuvant_label,c_adjuvant_description,c_vaccine_id,c_pathogen_id,c_curation_flag
1,2,VO_0000192,test,test2,211,8,11

c_vaxjo_name: 3 test rows

,c_vaxjo_id,c_components,c_function,c_dosage,c_safety,c_vaxjo_vo_id,c_vaxjo_name,c_submitted_by,c_submission_date,c_curation_flag,...,c_description,c_alternative_names,c_structure,c_appearance,c_molecular_weight,c_storage,c_stage_dev,c_location_licensed,c_host_licensed,c_host_licensed2
106,209,NaN,NaN,NaN,NaN,NaN,test adjuvant,joshuam1500@gmail.com,2025-05-01 09:36:00,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,134,NaN,NaN,NaN,NaN,NaN,test7,yongqunh@umich.edu,2022-03-11 23:54:00,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,133,NaN,NaN,NaN,NaN,NaN,test-7,yongqunh@umich.edu,2022-03-11 18:08:00,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

c_vaccine_name: 9 test rows

,c_vaccine_id,c_vaccine_name,c_type,c_is_combination_vaccine,c_description,c_adjuvant,c_storage,c_pathogen_id,c_virulence,c_preparation,...,c_route,c_vo_id,c_usage_age,c_model_host,c_preservative,c_allergen,c_preparation_vo_id,c_host_species2,c_cvx_code,c_cvx_desc
241,5591,test vaccine,"Live, attenuated vaccine",0,NaN,NaN,NaN,25,NaN,NaN,...,Intramuscular injection (i.m.),NaN,NaN,mouse,NaN,NaN,NaN,0,NaN,NaN
899,751,test222,"Live, attenuated vaccine",No,NaN,NaN,ddddddd,45,NaN,NaN,...,Intramuscular injection (i.m.),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
910,755,test11,"Live, attenuated vaccine",No,NaN,NaN,NaN,50,NaN,NaN,...,Intramuscular injection (i.m.),test111,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
911,756,test222,"Live, attenuated vaccine",No,NaN,NaN,NaN,50,NaN,NaN,...,Intramuscular injection (i.m.),test222,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
912,757,test333,"Live, attenuated vaccine",No,NaN,NaN,NaN,50,NaN,NaN,...,Intramuscular injection (i.m.),test333,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
913,758,test444,"Live, attenuated vaccine",No,NaN,NaN,NaN,50,NaN,NaN,...,Intramuscular injection (i.m.),test444,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
3119,3297,test,"Live, attenuated vaccine",0,NaN,NaN,NaN,217,NaN,NaN,...,Intramuscular injection (i.m.),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
4711,5585,Test vaccine for bug,"Live, attenuated vaccine",1,NaN,NaN,NaN,54,NaN,NaN,...,Intramuscular injection (i.m.),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
4712,5586,Test vaccine 2,"Live, attenuated vaccine",1,NaN,NaN,NaN,54,NaN,NaN,...,Intramuscular injection (i.m.),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN

c_pathogen_name: 1 test rows

,c_pathogen_id,c_pathogen_name,c_taxon_id,c_pathogenesis,c_disease_name,c_protective_immunity,c_submitted_by,c_submission_date,c_curation_flag,c_reviewer,c_host_range,c_full_text,c_introduction,c_gram,c_organism_type,c_preparation_vo_id,c_vaccine_vo_id,c_protein_vo_id
189,217,test,NaN,NaN,NaN,NaN,yongqunh@umich.edu,2011-09-07 17:19:02,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
def drop_test_rows(df, col):
    if col in df.columns:
        mask = df[col].astype(str).str.lower().str.startswith("test")
        return df[~mask]
    return df

df_adjuvant = drop_test_rows(df_adjuvant_raw, "c_adjuvant_label")
df_vaxjo   = drop_test_rows(df_vaxjo_raw, "c_vaxjo_name")
df_vaccine = drop_test_rows(df_vaccine_raw, "c_vaccine_name")
df_pathogen = drop_test_rows(df_pathogen_raw, "c_pathogen_name")

df_adjuvant.to_csv("Dataset/VIOLIN_12-10-2025/raw/t_adjuvant_202512101312_clean.csv", index=False, encoding="utf-8-sig")
df_vaxjo.to_csv("Dataset/VIOLIN_12-10-2025/raw/t_vaxjo_202512101311_clean.csv", index=False, encoding="utf-8-sig")
df_vaccine.to_csv("Dataset/VIOLIN_12-10-2025/raw/t_vaccine_202512101310_clean.csv", index=False, encoding="utf-8-sig")
df_pathogen.to_csv("Dataset/VIOLIN_12-10-2025/raw/t_pathogen_202512101313_clean.csv", index=False, encoding="utf-8-sig")

print("Saved cleaned files to raw/")
# Summaries
summarize_df(df_vaccine, "t_vaccine")
summarize_df(df_adjuvant, "t_adjuvant")
summarize_df(df_vaxjo, "t_vaxjo")
summarize_df(df_pathogen, "t_pathogen")

Saved cleaned files to raw/

=== t_vaccine ===
Number of rows: 5541
Number of columns: 31
Columns: ['c_vaccine_id', 'c_vaccine_name', 'c_type', 'c_is_combination_vaccine', 'c_description', 'c_adjuvant', 'c_storage', 'c_pathogen_id', 'c_virulence', 'c_preparation', 'c_brand_name', 'c_full_text', 'c_antigen', 'c_curation_flag', 'c_vector', 'c_proper_name', 'c_manufacturer', 'c_contraindication', 'c_status', 'c_location_licensed', 'c_host_species', 'c_route', 'c_vo_id', 'c_usage_age', 'c_model_host', 'c_preservative', 'c_allergen', 'c_preparation_vo_id', 'c_host_species2', 'c_cvx_code', 'c_cvx_desc']

=== t_adjuvant ===
Number of rows: 564
Number of columns: 7
Columns: ['c_adjuvant_id', 'c_adjuvant_vo_id', 'c_adjuvant_label', 'c_adjuvant_description', 'c_vaccine_id', 'c_pathogen_id', 'c_curation_flag']

=== t_vaxjo ===
Number of rows: 497
Number of columns: 22
Columns: ['c_vaxjo_id', 'c_components', 'c_function', 'c_dosage', 'c_safety', 'c_vaxjo_vo_id', 'c_vaxjo_name', 'c_submitted_by', 'c_submission_date', 'c_curation_flag', 'c_reviewer', 'c_preparation', 'c_description', 'c_alternative_names', 'c_structure', 'c_appearance', 'c_molecular_weight', 'c_storage', 'c_stage_dev', 'c_location_licensed', 'c_host_licensed', 'c_host_licensed2']

=== t_pathogen ===
Number of rows: 313
Number of columns: 18
Columns: ['c_pathogen_id', 'c_pathogen_name', 'c_taxon_id', 'c_pathogenesis', 'c_disease_name', 'c_protective_immunity', 'c_submitted_by', 'c_submission_date', 'c_curation_flag', 'c_reviewer', 'c_host_range', 'c_full_text', 'c_introduction', 'c_gram', 'c_organism_type', 'c_preparation_vo_id', 'c_vaccine_vo_id', 'c_protein_vo_id']

In [5]:
df_adjuvant_ext1 = pd.merge(
    df_adjuvant,
    df_vaxjo,
    how="left",
    left_on="c_adjuvant_vo_id",
    right_on="c_vaxjo_vo_id",
    suffixes=('', '_vaxjo')
)
df_adjuvant_ext1.head(2)

,c_adjuvant_id,c_adjuvant_vo_id,c_adjuvant_label,c_adjuvant_description,c_vaccine_id,c_pathogen_id,c_curation_flag,c_vaxjo_id,c_components,c_function,...,c_description,c_alternative_names,c_structure,c_appearance,c_molecular_weight,c_storage,c_stage_dev,c_location_licensed,c_host_licensed,c_host_licensed2
0,3,VO_0000142,Incomplete Freund's Adjuvant,Incomplete Freund's Adjuvant,446,8,10,9.0,Each ml contains .85 mL paraffin oil and 0.15 ...,When added to Freund's incomplete adjuvant wit...,...,"IFA types of adjuvant products have been, and ...","IFA, Incomplete Freund's Adjuvant",NaN,NaN,NaN,NaN,Research,NaN,NaN,NaN
1,4,VO_0000128,NaN,NaN,774,109,10,4.0,Aluminum Phosphate (Al(PO4),Aluminium phosphate (AP) adjuvant has a platy...,...,Aluminium phosphate (AP) adjuvant is amorphous...,"Adju-PhosÂ®, Al(PO)4",NaN,NaN,NaN,NaN,Licensed,NaN,2,NaN

In [6]:
def drop_identical_suffixed_columns(df, suffix):
    dropped = []
    for col in df.columns:
        if col.endswith(suffix):
            base_col = col.replace(suffix, '')
            if base_col in df.columns:
                same = df[col].fillna("__") == df[base_col].fillna("__")
                if same.all():
                    df.drop(columns=[col], inplace=True)
                    dropped.append(col)
    return dropped

# Example use:
dropped_cols = drop_identical_suffixed_columns(df_adjuvant_ext1, suffix = "_vaxjo")
print("Dropped columns:", dropped_cols)
df_adjuvant_ext1.head(2)

Dropped columns: []

,c_adjuvant_id,c_adjuvant_vo_id,c_adjuvant_label,c_adjuvant_description,c_vaccine_id,c_pathogen_id,c_curation_flag,c_vaxjo_id,c_components,c_function,...,c_description,c_alternative_names,c_structure,c_appearance,c_molecular_weight,c_storage,c_stage_dev,c_location_licensed,c_host_licensed,c_host_licensed2
0,3,VO_0000142,Incomplete Freund's Adjuvant,Incomplete Freund's Adjuvant,446,8,10,9.0,Each ml contains .85 mL paraffin oil and 0.15 ...,When added to Freund's incomplete adjuvant wit...,...,"IFA types of adjuvant products have been, and ...","IFA, Incomplete Freund's Adjuvant",NaN,NaN,NaN,NaN,Research,NaN,NaN,NaN
1,4,VO_0000128,NaN,NaN,774,109,10,4.0,Aluminum Phosphate (Al(PO4),Aluminium phosphate (AP) adjuvant has a platy...,...,Aluminium phosphate (AP) adjuvant is amorphous...,"Adju-PhosÂ®, Al(PO)4",NaN,NaN,NaN,NaN,Licensed,NaN,2,NaN

In [7]:
# Summaries
summarize_df(df_adjuvant_ext1, "df_adjuvant_ext1")

=== df_adjuvant_ext1 ===
Number of rows: 602
Number of columns: 29
Columns: ['c_adjuvant_id', 'c_adjuvant_vo_id', 'c_adjuvant_label', 'c_adjuvant_description', 'c_vaccine_id', 'c_pathogen_id', 'c_curation_flag', 'c_vaxjo_id', 'c_components', 'c_function', 'c_dosage', 'c_safety', 'c_vaxjo_vo_id', 'c_vaxjo_name', 'c_submitted_by', 'c_submission_date', 'c_curation_flag_vaxjo', 'c_reviewer', 'c_preparation', 'c_description', 'c_alternative_names', 'c_structure', 'c_appearance', 'c_molecular_weight', 'c_storage', 'c_stage_dev', 'c_location_licensed', 'c_host_licensed', 'c_host_licensed2']

In [8]:
df_adjuvant_ext2 = pd.merge(
    df_adjuvant_ext1,
    df_vaccine,
    how="left",
    on="c_vaccine_id",
    suffixes=('', '_vaccine')
)
df_adjuvant_ext2.head(2)

,c_adjuvant_id,c_adjuvant_vo_id,c_adjuvant_label,c_adjuvant_description,c_vaccine_id,c_pathogen_id,c_curation_flag,c_vaxjo_id,c_components,c_function,...,c_route,c_vo_id,c_usage_age,c_model_host,c_preservative,c_allergen,c_preparation_vo_id,c_host_species2,c_cvx_code,c_cvx_desc
0,3,VO_0000142,Incomplete Freund's Adjuvant,Incomplete Freund's Adjuvant,446,8,10,9.0,Each ml contains .85 mL paraffin oil and 0.15 ...,When added to Freund's incomplete adjuvant wit...,...,Intramuscular injection (i.m.),VO_0000436,NaN,NaN,NaN,NaN,VO_0011648,0,NaN,NaN
1,4,VO_0000128,NaN,NaN,774,109,10,4.0,Aluminum Phosphate (Al(PO4),Aluminium phosphate (AP) adjuvant has a platy...,...,Intramuscular injection (i.m.),VO_0000005,Adacel vaccine is indicated for active booster...,NaN,NaN,NaN,VO_0011597,0,"20, 115",NaN

In [9]:
# Example use:
dropped_cols = drop_identical_suffixed_columns(df_adjuvant_ext2, suffix = "_vaccine")
print("Dropped columns:", dropped_cols)
df_adjuvant_ext2.head(2)

Dropped columns: ['c_pathogen_id_vaccine']

,c_adjuvant_id,c_adjuvant_vo_id,c_adjuvant_label,c_adjuvant_description,c_vaccine_id,c_pathogen_id,c_curation_flag,c_vaxjo_id,c_components,c_function,...,c_route,c_vo_id,c_usage_age,c_model_host,c_preservative,c_allergen,c_preparation_vo_id,c_host_species2,c_cvx_code,c_cvx_desc
0,3,VO_0000142,Incomplete Freund's Adjuvant,Incomplete Freund's Adjuvant,446,8,10,9.0,Each ml contains .85 mL paraffin oil and 0.15 ...,When added to Freund's incomplete adjuvant wit...,...,Intramuscular injection (i.m.),VO_0000436,NaN,NaN,NaN,NaN,VO_0011648,0,NaN,NaN
1,4,VO_0000128,NaN,NaN,774,109,10,4.0,Aluminum Phosphate (Al(PO4),Aluminium phosphate (AP) adjuvant has a platy...,...,Intramuscular injection (i.m.),VO_0000005,Adacel vaccine is indicated for active booster...,NaN,NaN,NaN,VO_0011597,0,"20, 115",NaN

In [10]:
# Summaries
summarize_df(df_adjuvant_ext2, "df_adjuvant_ext2")

=== df_adjuvant_ext2 ===
Number of rows: 602
Number of columns: 58
Columns: ['c_adjuvant_id', 'c_adjuvant_vo_id', 'c_adjuvant_label', 'c_adjuvant_description', 'c_vaccine_id', 'c_pathogen_id', 'c_curation_flag', 'c_vaxjo_id', 'c_components', 'c_function', 'c_dosage', 'c_safety', 'c_vaxjo_vo_id', 'c_vaxjo_name', 'c_submitted_by', 'c_submission_date', 'c_curation_flag_vaxjo', 'c_reviewer', 'c_preparation', 'c_description', 'c_alternative_names', 'c_structure', 'c_appearance', 'c_molecular_weight', 'c_storage', 'c_stage_dev', 'c_location_licensed', 'c_host_licensed', 'c_host_licensed2', 'c_vaccine_name', 'c_type', 'c_is_combination_vaccine', 'c_description_vaccine', 'c_adjuvant', 'c_storage_vaccine', 'c_virulence', 'c_preparation_vaccine', 'c_brand_name', 'c_full_text', 'c_antigen', 'c_curation_flag_vaccine', 'c_vector', 'c_proper_name', 'c_manufacturer', 'c_contraindication', 'c_status', 'c_location_licensed_vaccine', 'c_host_species', 'c_route', 'c_vo_id', 'c_usage_age', 'c_model_host', 'c_preservative', 'c_allergen', 'c_preparation_vo_id', 'c_host_species2', 'c_cvx_code', 'c_cvx_desc']

In [11]:
df_adjuvant_ext3 = pd.merge(
    df_adjuvant_ext2,
    df_pathogen,
    how="left",
    on="c_pathogen_id",
    suffixes=('', '_pathogen')
)

df_adjuvant_ext3.head(2)

,c_adjuvant_id,c_adjuvant_vo_id,c_adjuvant_label,c_adjuvant_description,c_vaccine_id,c_pathogen_id,c_curation_flag,c_vaxjo_id,c_components,c_function,...,c_curation_flag_pathogen,c_reviewer_pathogen,c_host_range,c_full_text_pathogen,c_introduction,c_gram,c_organism_type,c_preparation_vo_id_pathogen,c_vaccine_vo_id,c_protein_vo_id
0,3,VO_0000142,Incomplete Freund's Adjuvant,Incomplete Freund's Adjuvant,446,8,10,9.0,Each ml contains .85 mL paraffin oil and 0.15 ...,When added to Freund's incomplete adjuvant wit...,...,10,NaN,Brucella has a broad host range infecting vert...,Brucella spp. Table of Contents General Infor...,"Brucella species are gram-negative, facultativ...",-,G- bacterium,VO_0012194,NaN,VO_0010758
1,4,VO_0000128,NaN,NaN,774,109,10,4.0,Aluminum Phosphate (Al(PO4),Aluminium phosphate (AP) adjuvant has a platy...,...,10,NaN,"Animal models of pertussis include primates, r...",Bordetella pertussis Table of Contents Genera...,"Bordetella pertussis is a Gram-negative, aerob...",-,G- bacterium,VO_0012192,NaN,VO_0010847

In [12]:
# Example use:
dropped_cols = drop_identical_suffixed_columns(df_adjuvant_ext3, suffix = "_pathogen")
print("Dropped columns:", dropped_cols)
df_adjuvant_ext3.head(2)

Dropped columns: []

,c_adjuvant_id,c_adjuvant_vo_id,c_adjuvant_label,c_adjuvant_description,c_vaccine_id,c_pathogen_id,c_curation_flag,c_vaxjo_id,c_components,c_function,...,c_curation_flag_pathogen,c_reviewer_pathogen,c_host_range,c_full_text_pathogen,c_introduction,c_gram,c_organism_type,c_preparation_vo_id_pathogen,c_vaccine_vo_id,c_protein_vo_id
0,3,VO_0000142,Incomplete Freund's Adjuvant,Incomplete Freund's Adjuvant,446,8,10,9.0,Each ml contains .85 mL paraffin oil and 0.15 ...,When added to Freund's incomplete adjuvant wit...,...,10,NaN,Brucella has a broad host range infecting vert...,Brucella spp. Table of Contents General Infor...,"Brucella species are gram-negative, facultativ...",-,G- bacterium,VO_0012194,NaN,VO_0010758
1,4,VO_0000128,NaN,NaN,774,109,10,4.0,Aluminum Phosphate (Al(PO4),Aluminium phosphate (AP) adjuvant has a platy...,...,10,NaN,"Animal models of pertussis include primates, r...",Bordetella pertussis Table of Contents Genera...,"Bordetella pertussis is a Gram-negative, aerob...",-,G- bacterium,VO_0012192,NaN,VO_0010847

In [13]:
# Summaries
summarize_df(df_adjuvant_ext3, "df_adjuvant_ext3")

=== df_adjuvant_ext3 ===
Number of rows: 602
Number of columns: 75
Columns: ['c_adjuvant_id', 'c_adjuvant_vo_id', 'c_adjuvant_label', 'c_adjuvant_description', 'c_vaccine_id', 'c_pathogen_id', 'c_curation_flag', 'c_vaxjo_id', 'c_components', 'c_function', 'c_dosage', 'c_safety', 'c_vaxjo_vo_id', 'c_vaxjo_name', 'c_submitted_by', 'c_submission_date', 'c_curation_flag_vaxjo', 'c_reviewer', 'c_preparation', 'c_description', 'c_alternative_names', 'c_structure', 'c_appearance', 'c_molecular_weight', 'c_storage', 'c_stage_dev', 'c_location_licensed', 'c_host_licensed', 'c_host_licensed2', 'c_vaccine_name', 'c_type', 'c_is_combination_vaccine', 'c_description_vaccine', 'c_adjuvant', 'c_storage_vaccine', 'c_virulence', 'c_preparation_vaccine', 'c_brand_name', 'c_full_text', 'c_antigen', 'c_curation_flag_vaccine', 'c_vector', 'c_proper_name', 'c_manufacturer', 'c_contraindication', 'c_status', 'c_location_licensed_vaccine', 'c_host_species', 'c_route', 'c_vo_id', 'c_usage_age', 'c_model_host', 'c_preservative', 'c_allergen', 'c_preparation_vo_id', 'c_host_species2', 'c_cvx_code', 'c_cvx_desc', 'c_pathogen_name', 'c_taxon_id', 'c_pathogenesis', 'c_disease_name', 'c_protective_immunity', 'c_submitted_by_pathogen', 'c_submission_date_pathogen', 'c_curation_flag_pathogen', 'c_reviewer_pathogen', 'c_host_range', 'c_full_text_pathogen', 'c_introduction', 'c_gram', 'c_organism_type', 'c_preparation_vo_id_pathogen', 'c_vaccine_vo_id', 'c_protein_vo_id']

In [14]:
def analyze_remaining_suffixed_columns(df, suffix, show_table=True):
    """
    Analyze remaining column pairs after dropping identicals.
    Compares base vs. suffixed column and returns match statistics.

    Args:
        df (pd.DataFrame): Input DataFrame
        suffix (str): Suffix to look for (e.g., "_vaxjo")
        show_table (bool): Whether to display the table

    Returns:
        pd.DataFrame: Summary comparison table
    """
    import pandas as pd

    results = []

    col_pairs = [
        (col.replace(suffix, ''), col)
        for col in df.columns
        if col.endswith(suffix) and col.replace(suffix, '') in df.columns
    ]

    for base_col, suffixed_col in col_pairs:
        base = df[base_col]
        comp = df[suffixed_col]

        both_empty = base.isna() & comp.isna()
        same_non_empty = (base == comp) & ~both_empty
        different = (base != comp) & ~(base.isna() | comp.isna())
        left_empty_only = base.isna() & ~comp.isna()
        right_empty_only = ~base.isna() & comp.isna()

        results.append({
            "Column": base_col,
            "Same (non-empty)": same_non_empty.sum(),
            "Different": different.sum(),
            "Both empty": both_empty.sum(),
            "Original empty only": left_empty_only.sum(),
            "Suffixed empty only": right_empty_only.sum()
        })

    summary_df = pd.DataFrame(results)
    summary_df = summary_df[[
        "Column", "Same (non-empty)", "Different",
        "Both empty", "Original empty only", "Suffixed empty only"
    ]].sort_values(by="Column").reset_index(drop=True)


    return summary_df

In [15]:
summary = analyze_remaining_suffixed_columns(df_adjuvant_ext1, suffix="_vaxjo")
summary

,Column,Same (non-empty),Different,Both empty,Original empty only,Suffixed empty only
0,c_curation_flag,511,69,0,0,22

In [16]:
summary = analyze_remaining_suffixed_columns(df_adjuvant_ext2, suffix="_vaccine")
summary

,Column,Same (non-empty),Different,Both empty,Original empty only,Suffixed empty only
0,c_curation_flag,532,70,0,0,0
1,c_description,0,220,52,15,315
2,c_location_licensed,1,11,446,106,38
3,c_preparation,0,117,188,80,217
4,c_storage,0,48,405,68,81

In [17]:
summary = analyze_remaining_suffixed_columns(df_adjuvant_ext3, suffix="_pathogen")
summary

,Column,Same (non-empty),Different,Both empty,Original empty only,Suffixed empty only
0,c_curation_flag,526,76,0,0,0
1,c_full_text,0,512,11,79,0
2,c_preparation_vo_id,0,291,89,222,0
3,c_reviewer,0,0,540,62,0
4,c_submission_date,0,580,0,22,0
5,c_submitted_by,68,512,0,22,0

In [18]:
print(df_adjuvant_ext3.columns)
df_adjuvant_ext3.head(5)

Index(['c_adjuvant_id', 'c_adjuvant_vo_id', 'c_adjuvant_label',
       'c_adjuvant_description', 'c_vaccine_id', 'c_pathogen_id',
       'c_curation_flag', 'c_vaxjo_id', 'c_components', 'c_function',
       'c_dosage', 'c_safety', 'c_vaxjo_vo_id', 'c_vaxjo_name',
       'c_submitted_by', 'c_submission_date', 'c_curation_flag_vaxjo',
       'c_reviewer', 'c_preparation', 'c_description', 'c_alternative_names',
       'c_structure', 'c_appearance', 'c_molecular_weight', 'c_storage',
       'c_stage_dev', 'c_location_licensed', 'c_host_licensed',
       'c_host_licensed2', 'c_vaccine_name', 'c_type',
       'c_is_combination_vaccine', 'c_description_vaccine', 'c_adjuvant',
       'c_storage_vaccine', 'c_virulence', 'c_preparation_vaccine',
       'c_brand_name', 'c_full_text', 'c_antigen', 'c_curation_flag_vaccine',
       'c_vector', 'c_proper_name', 'c_manufacturer', 'c_contraindication',
       'c_status', 'c_location_licensed_vaccine', 'c_host_species', 'c_route',
       'c_vo_id', 'c_usage_age', 'c_model_host', 'c_preservative',
       'c_allergen', 'c_preparation_vo_id', 'c_host_species2', 'c_cvx_code',
       'c_cvx_desc', 'c_pathogen_name', 'c_taxon_id', 'c_pathogenesis',
       'c_disease_name', 'c_protective_immunity', 'c_submitted_by_pathogen',
       'c_submission_date_pathogen', 'c_curation_flag_pathogen',
       'c_reviewer_pathogen', 'c_host_range', 'c_full_text_pathogen',
       'c_introduction', 'c_gram', 'c_organism_type',
       'c_preparation_vo_id_pathogen', 'c_vaccine_vo_id', 'c_protein_vo_id'],
      dtype='object')

,c_adjuvant_id,c_adjuvant_vo_id,c_adjuvant_label,c_adjuvant_description,c_vaccine_id,c_pathogen_id,c_curation_flag,c_vaxjo_id,c_components,c_function,...,c_curation_flag_pathogen,c_reviewer_pathogen,c_host_range,c_full_text_pathogen,c_introduction,c_gram,c_organism_type,c_preparation_vo_id_pathogen,c_vaccine_vo_id,c_protein_vo_id
0,3,VO_0000142,Incomplete Freund's Adjuvant,Incomplete Freund's Adjuvant,446,8,10,9.0,Each ml contains .85 mL paraffin oil and 0.15 ...,When added to Freund's incomplete adjuvant wit...,...,10,NaN,Brucella has a broad host range infecting vert...,Brucella spp. Table of Contents General Infor...,"Brucella species are gram-negative, facultativ...",-,G- bacterium,VO_0012194,NaN,VO_0010758
1,4,VO_0000128,NaN,NaN,774,109,10,4.0,Aluminum Phosphate (Al(PO4),Aluminium phosphate (AP) adjuvant has a platy...,...,10,NaN,"Animal models of pertussis include primates, r...",Bordetella pertussis Table of Contents Genera...,"Bordetella pertussis is a Gram-negative, aerob...",-,G- bacterium,VO_0012192,NaN,VO_0010847
2,5,VO_0000128,NaN,NaN,772,109,10,4.0,Aluminum Phosphate (Al(PO4),Aluminium phosphate (AP) adjuvant has a platy...,...,10,NaN,"Animal models of pertussis include primates, r...",Bordetella pertussis Table of Contents Genera...,"Bordetella pertussis is a Gram-negative, aerob...",-,G- bacterium,VO_0012192,NaN,VO_0010847
3,6,VO_0000128,Aluminum phosphate,DAPTACEL is a vaccine indicated for active imm...,775,109,10,4.0,Aluminum Phosphate (Al(PO4),Aluminium phosphate (AP) adjuvant has a platy...,...,10,NaN,"Animal models of pertussis include primates, r...",Bordetella pertussis Table of Contents Genera...,"Bordetella pertussis is a Gram-negative, aerob...",-,G- bacterium,VO_0012192,NaN,VO_0010847
4,7,VO_0000127,Aluminum Hydroxide,NaN,776,109,10,3.0,aluminum hydroxide Al(OH)3,Aluminum hydroxide adjuvants act by depot form...,...,10,NaN,"Animal models of pertussis include primates, r...",Bordetella pertussis Table of Contents Genera...,"Bordetella pertussis is a Gram-negative, aerob...",-,G- bacterium,VO_0012192,NaN,VO_0010847

In [19]:
print(df_adjuvant_ext3['c_organism_type'].value_counts(dropna=False))

c_organism_type
G- bacterium    182
G+ bacterium    130
virus           124
parasite        106
other            46
NaN              10
fungus            4
Name: count, dtype: int64

In [20]:
df_other = df_adjuvant_ext3[df_adjuvant_ext3['c_organism_type'] == 'other']

df_other[['c_pathogen_name', 'c_disease_name', 'c_pathogenesis', 'c_organism_type']].head(20)

,c_pathogen_name,c_disease_name,c_pathogenesis,c_organism_type
24,Allergy,Allergy,NaN,other
27,Allergy,Allergy,NaN,other
167,Cancer,Cancer,NaN,other
168,Cancer,Cancer,NaN,other
169,Cancer,Cancer,NaN,other
170,Cancer,Cancer,NaN,other
402,Cancer,Cancer,NaN,other
403,Cancer,Cancer,NaN,other
437,Cancer,Cancer,NaN,other
438,Cancer,Cancer,NaN,other
440,Cancer,Cancer,NaN,other
460,Cancer,Cancer,NaN,other
469,Cancer,Cancer,NaN,other
473,Cancer,Cancer,NaN,other
479,Cancer,Cancer,NaN,other
482,Allergy,Allergy,NaN,other
486,Cancer,Cancer,NaN,other
504,Atherosclerosis,"Atherosclerosis, arteriosclerotic vascular dis...",NaN,other
505,Atherosclerosis,"Atherosclerosis, arteriosclerotic vascular dis...",NaN,other
517,Cancer,Cancer,NaN,other

In [21]:
print(df_adjuvant_ext3['c_disease_name'].value_counts(dropna=False))

c_disease_name
Meningitis                   42
Cancer                       41
Malaria                      36
Influenza (flu)              32
Tetanus                      28
                             ..
Chlamydia                     1
COVID-19                      1
Respiratory tract disease     1
Hepatitis C                   1
Hepatitis E                   1
Name: count, Length: 82, dtype: int64

In [22]:
len(df_adjuvant_ext3)

602

In [23]:
infectious_types = ['G- bacterium', 'G+ bacterium', 'virus', 'parasite', 'fungus']
infectious_df = df_adjuvant_ext3[df_adjuvant_ext3['c_organism_type'].isin(infectious_types)]
len(infectious_df)
548

548

In [24]:
df_non_infectious = df_adjuvant_ext3[~df_adjuvant_ext3['c_organism_type'].isin(infectious_types)]
df_non_infectious['c_disease_name'].value_counts()

c_disease_name
Cancer                                                       41
Allergy                                                       3
Atherosclerosis, arteriosclerotic vascular disease (ASVD)     2
Name: count, dtype: int64

In [25]:
# 509+41+3+2 = 555 Gap is 10 to reach the total of 565. 
# Probably coming from the empty ones. 
# c_organism_type has 10 NaN

In [26]:
# NaN in c_disease_name
df_adjuvant_ext3['c_disease_name'].isna().sum()

np.int64(20)

In [27]:
infectious_types = ['G- bacterium', 'G+ bacterium', 'virus', 'parasite', 'fungus']
df_adjuvant_ext3['is_infectious'] = df_adjuvant_ext3['c_organism_type'].isin(infectious_types)

# Summary
infectious_count = df_adjuvant_ext3['is_infectious'].sum()
non_infectious_count = (~df_adjuvant_ext3['is_infectious']).sum()

print(f"Infectious: {infectious_count}")
print(f"Non-infectious or unknown: {non_infectious_count}")

Infectious: 546
Non-infectious or unknown: 56

In [28]:
infectious_df = df_adjuvant_ext3[df_adjuvant_ext3['is_infectious']]

infectious_df.to_csv(
    "Dataset/VIOLIN_12-10-2025/interim/infectious_diseases_subset.csv",
    index=False,
    encoding="utf-8-sig",     # safe for Excel
    #na_rep=''                 # blank for missing values
)

In [29]:
import pandas as pd
import re

# Load your DataFrame
df = infectious_df

# Define regex pattern for [Ref...] or [PubMed...]
pattern = r'\[(Ref\d+:[^\]]+|PubMed:[^\]]+)\]'

# Dictionary to store results
column_ref_counts = {}

# Loop through each column
for col in df.columns:
    # Drop NaNs and convert all entries to string, then join into one large string
    combined_text = ' '.join(df[col].dropna().astype(str))
    
    # Find all matches of the pattern
    matches = re.findall(pattern, combined_text)
    
    # Count unique matches
    unique_refs = set(matches)
    
    # Store the count
    column_ref_counts[col] = len(unique_refs)

# Convert result to a DataFrame for easy viewing (optional)
ref_counts_df = pd.DataFrame.from_dict(column_ref_counts, orient='index', columns=['unique_reference_count'])
ref_counts_df = ref_counts_df.sort_values(by='unique_reference_count', ascending=False)

# Show the result
print(ref_counts_df.head(50))

                          unique_reference_count
c_full_text_pathogen                        1213
c_full_text                                  290
c_antigen                                    137
c_adjuvant                                   136
c_preparation_vaccine                        125
c_introduction                               104
c_description_vaccine                         97
c_pathogenesis                                83
c_function                                    82
c_description                                 80
c_host_range                                  70
c_protective_immunity                         67
c_safety                                      62
c_components                                  53
c_adjuvant_description                        49
c_preparation                                 38
c_dosage                                      37
c_usage_age                                   32
c_contraindication                            31
c_storage                                     24
c_virulence                                   20
c_vector                                      18
c_structure                                   13
c_appearance                                   9
c_storage_vaccine                              5
c_allergen                                     1
c_preservative                                 1
c_adjuvant_label                               0
c_vaccine_id                                   0
c_pathogen_id                                  0
c_curation_flag                                0
c_vaxjo_id                                     0
c_adjuvant_vo_id                               0
c_adjuvant_id                                  0
c_reviewer                                     0
c_submitted_by                                 0
c_host_licensed                                0
c_location_licensed                            0
c_stage_dev                                    0
c_molecular_weight                             0
c_alternative_names                            0
c_submission_date                              0
c_vaxjo_vo_id                                  0
c_vaxjo_name                                   0
c_manufacturer                                 0
c_proper_name                                  0
c_curation_flag_vaccine                        0
c_brand_name                                   0
c_is_combination_vaccine                       0
c_type                                         0

In [30]:
import pandas as pd
import re


# Patterns
ref_pattern = r'\[(Ref\d+:[^\]]+)\]'
pubmed_pattern = r'\[(PubMed:[^\]]+)\]'

# Storage
stats = []

# Loop through each column
for col in df.columns:
    combined_text = ' '.join(df[col].dropna().astype(str))

    # Extract matches
    ref_matches = re.findall(ref_pattern, combined_text)
    pubmed_matches = re.findall(pubmed_pattern, combined_text)

    # Convert to sets to ensure uniqueness
    unique_ref = set(ref_matches)
    unique_pubmed = set(pubmed_matches)

    # Combine for total
    total_unique = unique_ref.union(unique_pubmed)

    # Store the result
    stats.append({
        'column': col,
        'total_unique_refs': len(total_unique),
        'ref_count': len(unique_ref),
        'pubmed_count': len(unique_pubmed),
        'has_ref': len(unique_ref) > 0,
        'has_pubmed': len(unique_pubmed) > 0
    })

# Convert to DataFrame for better display
ref_stats_df = pd.DataFrame(stats).sort_values(by='total_unique_refs', ascending=False)

# Show results
print(ref_stats_df.head(40))

                    column  total_unique_refs  ref_count  pubmed_count  \
68    c_full_text_pathogen               1213          1          1212
38             c_full_text                290          0           290
39               c_antigen                137        137             0
33              c_adjuvant                136        136             0
36   c_preparation_vaccine                125        125             0
69          c_introduction                104        104             0
32   c_description_vaccine                 97         97             0
60          c_pathogenesis                 83         83             0
9               c_function                 82         82             0
19           c_description                 80         80             0
67            c_host_range                 70         70             0
62   c_protective_immunity                 67         67             0
11                c_safety                 62         62             0
8             c_components                 53         53             0
3   c_adjuvant_description                 49         49             0
18           c_preparation                 38         38             0
10                c_dosage                 37         37             0
50             c_usage_age                 32         32             0
44      c_contraindication                 31         31             0
24               c_storage                 24         24             0
35             c_virulence                 20         20             0
41                c_vector                 18         18             0
21             c_structure                 13         13             0
22            c_appearance                  9          9             0
34       c_storage_vaccine                  5          5             0
53              c_allergen                  1          1             0
52          c_preservative                  1          1             0
2         c_adjuvant_label                  0          0             0
4             c_vaccine_id                  0          0             0
5            c_pathogen_id                  0          0             0
6          c_curation_flag                  0          0             0
7               c_vaxjo_id                  0          0             0
1         c_adjuvant_vo_id                  0          0             0
0            c_adjuvant_id                  0          0             0
17              c_reviewer                  0          0             0
14          c_submitted_by                  0          0             0
27         c_host_licensed                  0          0             0
26     c_location_licensed                  0          0             0
25             c_stage_dev                  0          0             0
23      c_molecular_weight                  0          0             0

    has_ref  has_pubmed
68     True        True
38    False        True
39     True       False
33     True       False
36     True       False
69     True       False
32     True       False
60     True       False
9      True       False
19     True       False
67     True       False
62     True       False
11     True       False
8      True       False
3      True       False
18     True       False
10     True       False
50     True       False
44     True       False
24     True       False
35     True       False
41     True       False
21     True       False
22     True       False
34     True       False
53     True       False
52     True       False
2     False       False
4     False       False
5     False       False
6     False       False
7     False       False
1     False       False
0     False       False
17    False       False
14    False       False
27    False       False
26    False       False
25    False       False
23    False       False

In [31]:
import pandas as pd

# Load your DataFrame
# df = pd.read_csv("your_file.csv")  # Adjust as needed

# Choose the index of the row you want to inspect (e.g., row with Ref1691)
# You can also search by content if you prefer (see below)
row_index = 0  # Change this to the index you want

# Optional: Find row containing a specific reference like "Ref1691"
# matches = df[df.astype(str).apply(lambda x: x.str.contains("Ref1691")).any(axis=1)]
# row_index = matches.index[0] if not matches.empty else None

# If index is valid, print full row content as one string
if row_index is not None:
    row = df.iloc[row_index]
    full_text = ' | '.join(row.dropna().astype(str))  # ' | ' used as separator
    print(f"\n🔍 Row {row_index} — Full Text Content:\n")
    print(full_text)
else:
    print("No matching row found.")

🔍 Row 0 — Full Text Content:

3 | VO_0000142 | Incomplete Freund's Adjuvant | Incomplete Freund's Adjuvant | 446 | 8 | 10 | 9.0 | Each ml contains .85 mL paraffin oil and 0.15 ml mannide monooleate. Freund's incomplete adjuvant lacks the mycobacteria found in Complete Freundâ€™s Adjuvant so it minimizes the side-effects. For this reason, Incomplete Freundâ€™s Adjuvant is used for the boost injections [Ref1697:Sigma Aldrich]. | When added to Freund's incomplete adjuvant with an antigen (e.g., ovalbumin) and injected into hind-foot pads of guinea pigs, this water-soluble adjuvant increases the amount of precipitating antibodies and induces hypersensitivity to ovalbumin and the biosynthesis of -y2-type precipitating antibodies. The water-soluble material has a stronger adjuvant activity than equal amounts of whole bacteria, cell walls, or waxes D, and seems to be the first well-defined, water-soluble, adjuvant-active fraction isolated from Mycobacteria [Ref1693:Adam et al., 1972]. | Unless otherwise indicated, 5-wk-old NOD mice were injected in the hind footpad or i.p. with 50 Âµ1 of an emulsion of CFA (containing Mycobacterium strain H37Ra), or IFA (DIFCO, Detroit, MI) in saline. [Ref1694:Qin et al., 1993] | A concern was the possible long-term effects of FIA on the incidence of cancer, autoimmunity and other diseases. US soldiers who received FIA with the influenza vaccine, and a control group ( 20,000 in each group) were followed for 16â€“18 years  and 35 years. No increase in the incidence of any disease or disease-specific death was observed. Regarding short-term effects, FIA-adjuvanted influenza vaccine caused only 40 severe local reactions (including sterile abscesses) in  1,000,000 vaccinated individuals and was safe (without severe local reactions) in the first trial of tetanus toxoid in FIA, which was carried out in Papua New Guinea. However, the second trial had a 59% incidence of severe local reactions (sterile abscesses and persistent painful granulomas at the injection site). At around the same time, a trial of cholera vaccine in FIA carried out in the Philippines was also associated with a high incidence of severe local reactions in the FIA group. In an attempt to explain the cause of this problem in the second tetanus vaccine trial, but not the first and not the influenza vaccine trial, it was suggested that the release of free fatty acids from mannide monooleate by an impure tetanus antigen might have caused the severe local reactogenicity. More-recent data suggest that high doses of antigen in another water-in-oil adjuvant (Montanide ISA 720) might also predispose to this complication [Ref1696:Miller et al., 2005]. | VO_0000142 | Freund's Incomplete Adjuvant | ulysseg@umich.edu | 2011-02-20 16:21:00 | 10.0 | When FIA or FCA was used, equal volumes of antigen (sometimes also containing an additional adjuvant dissolved or suspended in the saline) and oil were emulsified by homogenization for 2 min at full speed in an MSE blender. The water-in oil character of the emulsion was checked for its non-dispersibility in water. Adjuvants in saline were mixed with equal volumes of antigen [Ref1695:Bomford, 1980]. | IFA types of adjuvant products have been, and continue to be, used in veterinary vaccine products. Their continued use is based primarily on potency in vaccines where aluminum and saponin adjuvants-based products have failed. These products are typically composed of light mineral oils and purified emulsifiers, such as Montanide ISA 50, and as such, they do not irritate in an unacceptable manner [Ref1691:Jensen et al., 1998]. | IFA, Incomplete Freund's Adjuvant | Research | B. melitensis DNA vaccine encoding Omp31 boosted with Omp31 | DNA vaccine | No | A regimen of DNA prime and protein boost is followed, increasing the efficacy of the vaccine compared to DNA or protein alone [Ref855:Cassataro et al., 2007]. | Incomplete Freund's Adjuvant | For the propagation of plasmids, Escherichia coli strain JM109 was used. For the expression of the recombinant protein, strain BL21(DE3) was employed. Bacterial strains were routinely grown, and rOmp31 was obtained and treated as described by [Ref487:Estein et al., 2003]. Purity was determined by Coomassie blue staining as described by (Cassataro et al., 2005). The plasmid pCIOmp31 was obtained as described in [Ref489:Cassataro et al., 2005]. |  Vaccine Detail B. melitensis DNA vaccine encoding Omp31 boosted with Omp31 Vaccine Information Vaccine Ontology ID: VO_0000436 Type: DNA vaccine with recombinant protein Status: Research Antigen: Omp31 protein Adjuvant: incomplete Freund's adjuvant Adjuvant name: incomplete Freund's adjuvant VO adjuvant ID: VO_0000142 Description: Incomplete Freund's Adjuvant Preparation: For the propagation of plasmids, Escherichia coli strain JM109 was used. For the expression of the recombinant protein, strain BL21(DE3) was employed. Bacterial strains were routinely grown, and rOmp31 was obtained and treated as described by (Estein et al., 2003). Purity was determined by Coomassie blue staining as described by (Cassataro et al., 2005). The plasmid pCIOmp31 was obtained as described in (Cassataro et al., 2005). Immunization Route: Intramuscular injection (i.m.) Description: A regimen of DNA prime and protein boost is followed, increasing the efficacy of the vaccine compared to DNA or protein alone (Cassataro et al., 2007). Host Response Mouse Response Vaccination Protocol: BALB/c mice was immunized with an Omp31 DNA vaccine (pCIOmp31) followed by boosting with recombinant Omp31 (rOmp31) in incomplete Freund's adjuvant (Cassataro et al., 2007). Immune Response: Immunoglobulin G1 (IgG1) and IgG2a titers were higher in sera from pCIOmp31/rOmp31-immunized mice than in sera from mice immunized with pCIOmp31 or rOmp31 alone. Splenocytes from pCIOmp31/rOmp31-immunized mice produced significantly higher levels of gamma interferon than did those from mice given rOmp31 alone. In contrast, interleukin 2 (IL-2) production levels were comparable between the two groups of immunized mice. Cells from all immunized mice produced undetectable levels of IL-4. Notably, rOmp31 stimulated IL-10 production in the pCIOmp31/rOmp31-immunized group but not in the pCIOmp31- or rOmp31-immunized group. Although the prime-boost regimen induced specific cytotoxic responses, these responses could not reach the levels achieved by the pCIOmp31 immunization (Cassataro et al., 2007). Challenge Protocol: Immunized mice were challenged, by intravenous inoculation, with 1x105 B. melitensis H38S organisms or 1x105 B. ovis organisms. Mice were sacrificed 30 days after the bacterial challenge, and their spleens were removed, homogenized, plated, and incubated. The number of CFU per spleen or liver was counted, and the results were given as the mean log number of CFU (Cassataro et al., 2007). Efficacy: pCIOmp31 priming followed by rOmp31 boosting led to moderately improved protection against a challenge with B. ovis or B. melitensis (Cassataro et al., 2007). References Cassataro et al., 2005: Cassataro J, Velikovsky CA, de la Barrera S, Estein SM, Bruno L, Bowden R, Pasquevich KA, Fossati CA, Giambartolomei GH. A DNA vaccine coding for the Brucella outer membrane protein 31 confers protection against B. melitensis and B. ovis infection by eliciting a specific cytotoxic response. Infection and immunity. 2005 Oct; 73(10); 6537-46. [PubMed: 16177328]. Cassataro et al., 2007: Cassataro J, Velikovsky CA, Bruno L, Estein SM, de la Barrera S, Bowden R, Fossati CA, Giambartolomei GH. Improved immunogenicity of a vaccination regimen combining a DNA vaccine encoding Brucella melitensis outer membrane protein 31 (Omp31) and recombinant Omp31 boosting. Clinical and vaccine immunology : CVI. 2007; 14(7); 869-874. [PubMed: 17428946]. Estein et al., 2003: Estein SM, Cassataro J, Vizcaino N, Zygmunt MS, Cloeckaert A, Bowden RA. The recombinant Omp31 from Brucella melitensis alone or associated with rough lipopolysaccharide induces protection against Brucella ovis infection in BALB/c mice. Microbes and infection / Institut Pasteur. 2003 Feb; 5(2); 85-93. [PubMed: 12650766].  | Omp31 protein | 10 | pCI-neo prime, recombinant protein boost [Ref489:Cassataro et al., 2005] | Research | 0 | Intramuscular injection (i.m.) | VO_0000436 | VO_0011648 | 0 | Brucella spp. | 234.0 | The mechanism of Brucella pathogenesis and infection of natural animal hosts is not completely understood [Ref410:Corbel, 1997]. It is well accepted that its pathogenesis relies on its ability to live and replicate inside the vacuolar phagocytic compartment of macrophages [Ref412:Kohler et al., 2002]. The host macrophage-Brucella interaction is critical for establishment of chronic Brucella infections. The Type IV secretion system encoded by the virB operon and the two-component regulatory system encoded by the bvrRS operon are required for successful replication of Brucella in macrophages. Smooth Brucella strains with intact lipopolysaccharide (LPS) O-side chains are virulent and invade macrophages through lipid rafts. On entry into the macrophage, Brucella reside in an acidified compartment that fuses with components of the early endosomal pathway. The majority of Brucella die at the early infection stage. A subpopulation of virulent Brucella strains is trafficked to an intracellular compartment known as the replicative phagosome (brucellosome) through continual interactions between the Brucella-containing vacuoles and the endoplasmic reticulum of the host macrophages. Once inside the replicative phagosome, Brucella are resistant to further attack and rapidly propagate. Virulent Brucella also inhibit macrophage apoptosis that in turn favors pathogen survival and replication. Brucella also infects placental trophoblast cells where acute infection leads to abortion and disease transmission [Ref411:Roop et al., 2004]. | Brucellosis | Both humoral and cell-mediated immune responses can influence the course of a Brucella infection, cell-mediated immune responses are essential for clearance of intracellular Brucella [Ref11:Schurig et al., 2002].   | yongqunh@umich.edu | 2008-01-23 14:56:37 | 10 | Brucella has a broad host range infecting vertebrate animal species and humans. Brucella infections are most often identified in humans, cattle, swine, goats, sheep, deer, caribou, elk, dogs and coyotes. There are six Brucella species based on the preferential host specificity: B. melitensis (goats), B. abortus (cattle), B. suis (swine), B. canis (dogs), B. ovis (sheep) and B. neotomae (desert mice). The first four species are pathogenic and exhibit a decreasing order of severity in humans.  Therefore, brucellosis is a zoonotic disease [Ref410:Corbel, 1997]. Mouse models are often used in Brucella vaccine research. BALB/c and C57BL/10 mice differ in their abilities to induce immune responses and protection against virulent Brucella infections [Ref413:Fernandes et al., 1996] [Ref415:Li, 1991] [Ref414:Montaraz et al., 1986]. |  Brucella spp. Table of Contents General Information NCBI Taxonomy ID Disease Introduction Microbial Pathogenesis Host Ranges and Animal Models Host Protective Immunity Vaccine Related Pathogen Genes RL3382 sadfasfd bcsp31 from Brucella (Other) cp24 from Brucella melitensis (Other) groEL from Brucella abortus (Other) AsnC (Protective antigen) B. abortus strain 19 L7/L12 (Protective antigen) B. melitensis M5 P39 (Protective antigen) Bfr from B. abortus S19 (Protective antigen) Bfr from B. melitensis biovar Abortus 2308 (Protective antigen) Bp26 (Protective antigen) cobB (Protective antigen) DnaK (Protective antigen) Gap (Protective antigen) IalB (Protective antigen) Omp16 (Protective antigen) Omp19 (Protective antigen) Omp25 (Protective antigen, Virmugen) Omp31 (Protective antigen) ORF (Protective antigen) RplL (Protective antigen) RpsL (Protective antigen) SodC from B. abortus strain 2308 (Protective antigen) SurA (Protective antigen) Tig (Protective antigen) znuA (Protective antigen, Virmugen) asp24 (Virmugen) bp26 (Virmugen) exsA (Virmugen) manA (Virmugen) manB (Virmugen) mucR (Virmugen) omp31 (Virmugen) pgk (Virmugen) pgm (Virmugen) purE (Virmugen) purK (Virmugen) virB2 (Virmugen) VjbR (Virmugen) vjbR (Virmugen) Vaccine Related Host Genes ANXI BAK1 Ccl2 Ccl3 Cxcl10 Cxcl9 Ifng (Interferon gamma) IgG Ighg1 Ighv1-9 Il10 (interleukin 10) Il12b Il18 Il2 Il4 (interleukin 4) Il5 TLR10 Vaccine Information B. abortus and B. melitensis mutants with unmarked deletion of asp24, virB2, or manBA B. abortus DNA vaccine encoding RplL and Omp16 B. abortus DNA vaccine expressiong BCSP31, SOD and L7/L12 B. abortus DNA vaccine pcDNA-SOD B. abortus DNA vaccine pcI-p39 encoding P39 (periplasmic-binding protein) B. abortus P39 deletion vaccine B. abortus pcDNA-BLS B. abortus strain 19 B. abortus strain 45/20 B. abortus subunit vaccine using L7/L12 B. abortus vaccine strain RB51 B. melitensis 16M DNA vaccine expressing Omp31 B. melitensis bp26 and TF Nasal Vaccine B. melitensis DNA vaccine encoding Omp31 boosted with Omp31 B. melitensis lipopolysaccharide (LPS) vaccine B. melitensis LPS-GBOMP B. melitensis P39 deletion vaccine B. melitensis P39 protein vaccine B. melitensis strain VTRM1 B. melitensis vaccine strain Rev. 1 B. melitensis with deleted bp26 (CGV26) B. melitensis WR201 (16MÎ”purEK) B. suis strain 2 B. suis strain VTRS1 Brucella abortus bacA mutant Brucella abortus exsA mutant vaccine Brucella abortus pgk mutant vaccine Brucella abortus pgm mutant vaccine Brucella abortus S19 vjbR mutant vaccine Brucella Abortus Strain 19, Live Culture Vaccine (USDA: 1251.01) Brucella Abortus Strain 19, Live Culture, Reduced Dose Vaccine (USDA: 1251.02) Brucella Abortus Strain RB-51, Live Culture Vaccine (USDA: 1261.00) Brucella DNA vaccine encoding chimera BLSOmp31 Brucella melitensis bp26 mutant vaccine Brucella melitensis mucR mutant vaccine Brucella melitensis omp25 mutant vaccine Brucella melitensis omp31 mutant vaccine Brucella ovis Microparticle Subunit Vaccine Brucella recombinant SurA protein vaccine CGV2631 Divalent DNA B. abortus Vaccine pcDNA3.1-L7/L12-Omp16 DNA vaccine encoding L7/L12-P39 E. coli Escheriosome-mediated Cytosolic Delivery of recombinant Brucella rL7/L12 Protein Live attenuated B. abortus with deletion of znuA Live, Attenuated Rifampin-Resistant Rough Mutants of Brucella melitensis Microencapsulated B. melitensis vjbR mutant vaccine NPAP Brucella vaccine Porin and S-LPS Extracted from Virulent Brucella abortus 2308 Recombinant B. abortus AsnC protein with CFA/IFA adjuvant Recombinant B. abortus CobB protein with CFA/IFA adjuvant Recombinant B. abortus RB51SOD Recombinant B. abortus RB51WboA Recombinant Brucella DnaK protein vaccine Recombinant chimera vaccine BLSOmp31 Recombinant O. anthropi 49237SOD References I. General Information 1. NCBI Taxonomy ID: 234 2. Disease: Brucellosis 3. Introduction Brucella species are gram-negative, facultative intracellular bacteria that cause brucellosis (or called Malta fever, undulant fever, Bang's disease, Mediterranean fever ) in humans and animals (Corbel, 1997). B. melitensis, B. abortus, B. suis, and B. canis are pathogenic to humans. The first three species have been identified as priority agents amenable for use in biological warfare and bio-terrorism, and are listed as NIAID and CDC category B priority pathogens. To date, there is no safe, effective Brucella vaccine available for human use. The vaccine strains used in animals are considered to be too virulent and unsafe for humans (Schurig et al., 1991). Novel vaccines that are non-infectious to humans but effective in stimulating a broad protective immune response are needed. 4. Microbial Pathogenesis The mechanism of Brucella pathogenesis and infection of natural animal hosts is not completely understood (Corbel, 1997). It is well accepted that its pathogenesis relies on its ability to live and replicate inside the vacuolar phagocytic compartment of macrophages (Kohler et al., 2002). The host macrophage-Brucella interaction is critical for establishment of chronic Brucella infections. The Type IV secretion system encoded by the virB operon and the two-component regulatory system encoded by the bvrRS operon are required for successful replication of Brucella in macrophages. Smooth Brucella strains with intact lipopolysaccharide (LPS) O-side chains are virulent and invade macrophages through lipid rafts. On entry into the macrophage, Brucella reside in an acidified compartment that fuses with components of the early endosomal pathway. The majority of Brucella die at the early infection stage. A subpopulation of virulent Brucella strains is trafficked to an intracellular compartment known as the replicative phagosome (brucellosome) through continual interactions between the Brucella-containing vacuoles and the endoplasmic reticulum of the host macrophages. Once inside the replicative phagosome, Brucella are resistant to further attack and rapidly propagate. Virulent Brucella also inhibit macrophage apoptosis that in turn favors pathogen survival and replication. Brucella also infects placental trophoblast cells where acute infection leads to abortion and disease transmission (Roop et al., 2004). 5. Host Ranges and Animal Models Brucella has a broad host range infecting vertebrate animal species and humans. Brucella infections are most often identified in humans, cattle, swine, goats, sheep, deer, caribou, elk, dogs and coyotes. There are six Brucella species based on the preferential host specificity: B. melitensis (goats), B. abortus (cattle), B. suis (swine), B. canis (dogs), B. ovis (sheep) and B. neotomae (desert mice). The first four species are pathogenic and exhibit a decreasing order of severity in humans. Therefore, brucellosis is a zoonotic disease (Corbel, 1997). Mouse models are often used in Brucella vaccine research. BALB/c and C57BL/10 mice differ in their abilities to induce immune responses and protection against virulent Brucella infections (Fernandes et al., 1996; Li, 1991; Montaraz et al., 1986). 6. Host Protective Immunity Both humoral and cell-mediated immune responses can influence the course of a Brucella infection, cell-mediated immune responses are essential for clearance of intracellular Brucella (Schurig et al., 2002). II. Vaccine Related Pathogen Genes 1. AsnC Gene Name : AsnC Sequence Strain (Species/Organism) : Brucella melitensis biovar Abortus 2308 NCBI Gene ID : 3788213 NCBI Protein GI : 82700464 Locus Tag : BAB1_1688 Genbank Accession : AM040264 Protein Accession : YP_415038 Taxonomy ID : 359391 Chromosome No : I Gene Starting Position : 1633929 Gene Ending Position : 1634399 Gene Strand (Orientation) : - Protein Name : AsnC family regulatory protein Protein pI : 5.32 Protein Weight : 15857.78 Protein Length : 156 DNA Sequence : Show Sequence >gi|82698932:1633929-1634399 Brucella melitensis biovar Abortus 2308 chromosome chromosome I, complete sequence
TCTAACGCCCATCCAGCGGGACGGCTGTGGTGTCCTTGATCTCTTCCATCACGAAAGAGGCCGATACATC
CGATAGCGGTACACAGGCTATGAGGCGCTGGTAGAGCCGGTCATAAGCTCTGACATCGGAAATGCGTGCC
TTCAGCACATAGTCCAGATCGCCGGTCATGCGATAGGCGCCGACGATTTCCGGGAAGCGAGCCACGGCAG
CGCGGAATTTGTTCAGCCATTCGGGATCATGGGCGGAGGTGCGCACCAGAATGAAAACCGAGAGGCCATA
GCCGACCATTTCCGCATCCACCAGCGCCACGCGACCTTTGATGACGCCATCGTCTTCCATGCGCTTTACG
CGCCGCCAGCAGGCATTGCGCGAAAGATTCACCCGTTCGGAAAGGGAATCAACCGACAAAGTGCCGTCGT
TTTGCAACTCAGCCAGGATTTTTCGGTCTATATCGTCCATAGATGCTGTCA Protein Sequence : Show Sequence >gi|82700464|ref|YP_415038.1| AsnC family regulatory protein [Brucella melitensis biovar Abortus 2308]
MTASMDDIDRKILAELQNDGTLSVDSLSERVNLSRNACWRRVKRMEDDGVIKGRVALVDAEMVGYGLSVF
ILVRTSAHDPEWLNKFRAAVARFPEIVGAYRMTGDLDYVLKARISDVRAYDRLYQRLIACVPLSDVSASF